STORAGE_SERVICE_URL    = 'http://localhost:8082'
DOWNLOAD_FILE_ENDPOINT = '/file/read'
CREATE_FILE_ENDPOINT   = '/file/create'
UPDATE_FILE_ENDPOINT   = 'file/update'
DELETE_FILE_ENDPOINT   = 'file/delete'
MATCH_FILE_ENDPOINT    = 'file/match-filename'